# Generated by Django 5.2.3 on 2025-06-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuexamattempt',
            name='selected_questions',
            field=models.ManyToManyField(related_name='attempts', to='questions.question_db'),
        ),
    ]
