# Generated by Django 5.2.3 on 2025-06-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_stuexamattempt_selected_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuexamattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
