# Generated by Django 5.2.3 on 2025-06-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_stuexamattempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_question',
            name='llm_explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stu_question',
            name='marks_awarded',
            field=models.FloatField(default=0),
        ),
    ]
