# Generated by Django 5.2.3 on 2025-06-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_db',
            name='solution',
            field=models.TextField(blank=True, help_text='Detailed explanation of the correct answer', null=True),
        ),
    ]
