# Generated by Django 5.2.3 on 2025-06-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_db_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_db',
            name='optionA',
            field=models.TextField(help_text='Option A (supports HTML/markdown formatting)'),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionB',
            field=models.TextField(help_text='Option B (supports HTML/markdown formatting)'),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionC',
            field=models.TextField(help_text='Option C (supports HTML/markdown formatting)'),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionD',
            field=models.TextField(help_text='Option D (supports HTML/markdown formatting)'),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='question',
            field=models.TextField(help_text='Question text (supports HTML/markdown formatting)'),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='solution',
            field=models.TextField(blank=True, help_text='Detailed explanation of the correct answer (supports HTML/markdown formatting)', null=True),
        ),
    ]
