# Generated by Django 5.2.3 on 2025-06-21 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_db_optiona_alter_question_db_optionb_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question_db',
            index=models.Index(fields=['professor'], name='questions_q_profess_c6182a_idx'),
        ),
        migrations.AddIndex(
            model_name='question_db',
            index=models.Index(fields=['qno'], name='questions_q_qno_0d5103_idx'),
        ),
    ]
