# Generated by Django 5.2.3 on 2025-06-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_db_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_db',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question_db',
            name='short_answer_expected',
        ),
        migrations.AddField(
            model_name='question_db',
            name='mcq_answer',
            field=models.CharField(blank=True, help_text='Correct option (A/B/C/D) for MCQ', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question_db',
            name='short_answer',
            field=models.TextField(blank=True, help_text='Expected/model answer for short answer questions', null=True),
        ),
    ]
