# Generated by Django 5.2.3 on 2025-06-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_question_db_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_db',
            name='mcq_answer',
            field=models.CharField(blank=True, help_text='Correct option for MCQ (A/B/C/D)', max_length=1, null=True),
        ),
    ]
