# Generated by Django 5.2.3 on 2025-06-23 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_topic'),
        ('questions', '0007_alter_question_db_mcq_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_db',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='course.topic'),
        ),
        migrations.AddField(
            model_name='question_paper',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='course.topic'),
        ),
    ]
