# Generated by Django 5.2.3 on 2025-06-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_question_db_topic_question_paper_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_model',
            name='num_questions',
            field=models.PositiveIntegerField(default=10, help_text='Number of random questions to select for this exam. Must be less than or equal to the number of questions in the question paper.'),
        ),
    ]
