# Generated by Django 5.2.3 on 2025-06-21 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_score', models.IntegerField()),
                ('grade_letter', models.CharField(max_length=1)),
                ('gp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('credit_units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_score', models.FloatField()),
                ('test_score', models.FloatField()),
                ('exam_score', models.FloatField()),
                ('is_carry_over', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultprocessing.resultcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultprocessing.resultstudent')),
            ],
        ),
    ]
